### ISSUE TITLE
Android Auto breaking errors with rendering in latest React Native

### ISSUE THREAD

**Issue by blakecallens** [birkir/react-native-carplay#200]
**Describe the bug**
After manually implementing PR #196, Android Auto is no longer crashing the app, but the ListTemplate's `onItemSelect` is not being triggered when an item is tapped. In addition, the following error is displayed on the phone: `"Android Auto" has not been registered.` (see screenshot below). This is regardless of the content of the list, including the example template. This may have to do with using React Native 74, which introduces a new version of the rendering engine.

**To Reproduce**
1. Implement PR #196 
2. Add a ListTemplate to the app and build
3. Open the Desktop Head Unit
4. The ListTemplate will render and be scrollable, but will not receive selection
5. A component registry error will display on the phone

**Expected behavior**
The ListTemplate should receive interaction and no errors should display on the phone.

**Screenshots/Videos**
<img width="399" alt="Screenshot 2024-07-18 at 1 15 14 PM" src="https://github.com/user-attachments/assets/603976ed-5f2b-45c2-93a1-fa174ba9a5a5">

**CarPlay (please complete the following information):**
 - Device: Desktop Head Unit
 - OS version: 14
 - RNCarPlay version: All versions >= 2.4.0

**Android Auto (please complete the following information):**
 - Device: Samsung Galaxy A15
 - Android Version: 14
 - RNCarPlay version: All versions >= 2.4.0

**Comment by Vikmanatus** [comment]
Hello,

On what `react-native` version are you facing this error ?

**Comment by EliG-TA** [comment]
@blakecallens Hey, I had the same issue. I managed to work around it by initiating as follows:

 ```
useEffect(() => {
    function onConnect() {
      CarPlay.setRootTemplate(tabTemplate, true);
      console.log("CarPlay connected");
    }
    function onDisconnect() {}

    function deviceCarPlayRegistering() {
      CarPlay.registerOnConnect(onConnect);
      CarPlay.registerOnDisconnect(onDisconnect);
    }
    if (Platform.OS === "android") {
      AppRegistry.registerRunnable("AndroidAuto", () => {
        deviceCarPlayRegistering();
        return;
      });
    } else {
      deviceCarPlayRegistering();
    }

    return () => {
      console.log("hello world");
      CarPlay.unregisterOnConnect(onConnect);
      CarPlay.unregisterOnDisconnect(onDisconnect);
    };
  }, []);
```

I hope that helps!

**Comment by Vikmanatus** [comment]
Than you very much for your response ! @EliG-TA

**Comment by bilalshams7** [comment]
> @blakecallens Hey, I had the same issue. I managed to work around it by initiating as follows:
> 
> ```
> useEffect(() => {
>    function onConnect() {
>      CarPlay.setRootTemplate(tabTemplate, true);
>      console.log("CarPlay connected");
>    }
>    function onDisconnect() {}
> 
>    function deviceCarPlayRegistering() {
>      CarPlay.registerOnConnect(onConnect);
>      CarPlay.registerOnDisconnect(onDisconnect);
>    }
>    if (Platform.OS === "android") {
>      AppRegistry.registerRunnable("AndroidAuto", () => {
>        deviceCarPlayRegistering();
>        return;
>      });
>    } else {
>      deviceCarPlayRegistering();
>    }
> 
>    return () => {
>      console.log("hello world");
>      CarPlay.unregisterOnConnect(onConnect);
>      CarPlay.unregisterOnDisconnect(onDisconnect);
>    };
>  }, []);
> ```
> 
> I hope that helps!

@EliG-TA hey,

i had this working perfectly in older android devices, But crashing in android 14 device. Do you have any idea why this is happening? 

Thanks in advance.

**Comment by EliG-TA** [comment]
@bilalshams7 I have not tried it myself, although you can try something like this in the app entry point file: 
 
```
import ActualCarPlayCode from "./CarPlay";
AppRegistry.registerComponent("CarPlay", () => ActualCarPlayCode);
```

**Comment by accesssolid** [comment]
> > [@blakecallens](https://github.com/blakecallens) Hey, I had the same issue. I managed to work around it by initiating as follows:
> > ```
> > useEffect(() => {
> >    function onConnect() {
> >      CarPlay.setRootTemplate(tabTemplate, true);
> >      console.log("CarPlay connected");
> >    }
> >    function onDisconnect() {}
> > 
> >    function deviceCarPlayRegistering() {
> >      CarPlay.registerOnConnect(onConnect);
> >      CarPlay.registerOnDisconnect(onDisconnect);
> >    }
> >    if (Platform.OS === "android") {
> >      AppRegistry.registerRunnable("AndroidAuto", () => {
> >        deviceCarPlayRegistering();
> >        return;
> >      });
> >    } else {
> >      deviceCarPlayRegistering();
> >    }
> > 
> >    return () => {
> >      console.log("hello world");
> >      CarPlay.unregisterOnConnect(onConnect);
> >      CarPlay.unregisterOnDisconnect(onDisconnect);
> >    };
> >  }, []);
> > ```
> > 
> > 
> >     
> >   
> > I hope that helps!
> 
> [@EliG-TA](https://github.com/EliG-TA) hey,
> 
> i had this working perfectly in older android devices, But crashing in android 14 device. Do you have any idea why this is happening?
> 
> Thanks in advance.

@bilalshams7 did you got any solution on this ?

**Comment by waldi** [comment]
Facing the same issue - has anyone been able to solve it?

**Comment by forki** [comment]
@blakecallens since the PR is not on npm - is there a way to use the github code in package.json? I tried but failed

**Comment by forki** [comment]
workaround: yarn add 'https://gitpkg.vercel.app/birkir/react-native-carplay/packages/react-native-carplay?master'

**Comment by forki** [comment]
@blakecallens did you see https://github.com/birkir/react-native-carplay/issues/156#issuecomment-1998896936

**Comment by phamdungabc** [comment]
Hello,
I’m still encountering this error in React Native version 0.76.9


`kotlin.UninitializedPropertyAccessException: lateinit property carContext has not been initialized

at org.birkir.carplay.CarPlayModule.createScreen (CarPlayModule.kt:297)

at org.birkir.carplay.CarPlayModule.createTemplate$lambda$0 (CarPlayModule.kt:114)

at org.birkir.carplay.CarPlayModule.$r8$lambda$9sex2LVUDdPHzECudMLMkKLR60w Source:0)

at org.birkir.carplay.CarPlayModule$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)

at android.os.Handler.handleCallback (Handler.java:942)

at android.os.Handler.dispatchMessage(Handler.java:99)

at android.os.Looper.loopOnce (Looper.java:240)

at android.os.Looper.loop (Looper.java:351)

at android.app.ActivityThread.main (ActivityThread.java:8423) <1 internal line>

at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)`

**Comment by GeoffreyFardeau** [comment]
Got the same issue, if i use CarPlay.setRootTemplate( )

instant crash..
